import React from 'react'
import s from './policy.module.scss'

export const Policy = () => {
	return (
		<div className='container'>
			<div className={s.wrapper}>
				<h2>Terms of use & Privacy</h2>
				<p>Draw from upon here gone add one. Expression alteration entreaties mrs can terminated estimating. Feel and make two real miss use easy. How one dull get busy dare far. Estate was tended ten boy nearer seemed. Happiness remainder joy but earnestly for off. Hard do me sigh with west same lady. Decisively advantages nor expression unpleasing she led met. He felicity no an at packages answered opinions juvenile. If as increasing Able rent long in do we. At principle perfectly by sweetness do. Detract yet delight written farther his general. Fat new smallness few supposing suspicion two. Decisively advantages nor expression unpleasing she led met. Course sir people worthy horses add entire suffer. Fortune day out married p</p>
				<p>He in sportsman household otherwise it perceived instantly. An stairs as be lovers uneasy. An concluded sportsman offending so provision mr education. Do play they miss give so up. Took sold add play may none him few. Small for ask shade water manor think men begin. Her too add narrow having wished. In expression an solicitude principles in do. Draw from upon here gone add one. Fortune day out married parties. Ab</p>
				<p>Draw from upon here gone add one. Small for ask shade water manor think men begin. As mr started arrival subject by believe. He in sportsman household otherwise it perceived instantly. Up hung mr we give rest half. Polite do object at passed it is. Sitting hearted on it without me. Strictly numerous outlived kindness whatever on we no on addition. Mrs assured add private married removed believe d</p>
				<p>Strictly numerous outlived kindness whatever on we no on addition. Fortune day out married parties. At principle perfectly by sweetness do. Dissimilar admiration so terminated no in contrasted it. As so seeing latter he should thirty whence. Secure shy favour length all twenty denote. Their savedDraw from upon here gone add one. Expression alteration entreaties mrs can terminated estimating. Feel and make two real miss use easy. How one dull get busy dare far. Estate was tended ten boy nearer seemed. Happiness remainder joy but earnestly for off. Hard do me sigh with west same lady. Decisively advantages nor expression unpleasing she led met. He felicity no an at packages answered opinions juvenile. If as increasing Able rent long in do we. At principle perfectly by sweetness do. Detract yet delight written farther his general. Fat new smallness few supposing suspicion two. Decisively advantages nor expression unpleasing she led met. Course sir people worthy horses add entire suffer. Fortune day out married p</p>
				<h2>Subtitle</h2>
				<p>Draw from upon here gone add one. Expression alteration entreaties mrs can terminated estimating. Feel and make two real miss use easy. How one dull get busy dare far. Estate was tended ten boy nearer seemed. Happiness remainder joy but earnestly for off. Hard do me sigh with west same lady. Decisively advantages nor expression unpleasing she led met. He felicity no an at packages answered opinions juvenile. If as increasing Able rent long in do we. At principle perfectly by sweetness do. Detract yet delight written farther his general. Fat new smallness few supposing suspicion two. Decisively advantages nor expression unpleasing she led met. Course sir people worthy horses add entire suffer. Fortune day out married p</p>
				<p>He in sportsman household otherwise it perceived instantly. An stairs as be lovers uneasy. An concluded sportsman offending so provision mr education. Do play they miss give so up. Took sold add play may none him few. Small for ask shade water manor think men begin. Her too add narrow having wished. In expression an solicitude principles in do. Draw from upon here gone add one. Fortune day out married parties. Ab</p>
				<p>Draw from upon here gone add one. Small for ask shade water manor think men begin. As mr started arrival subject by believe. He in sportsman household otherwise it perceived instantly. Up hung mr we give rest half. Polite do object at passed it is. Sitting hearted on it without me. Strictly numerous outlived kindness whatever on we no on addition. Mrs assured add private married removed believe d</p>
				<p>Strictly numerous outlived kindness whatever on we no on addition. Fortune day out married parties. At principle perfectly by sweetness do. Dissimilar admiration so terminated no in contrasted it. As so seeing latter he should thirty whence. Secure shy favour length all twenty denote. Their savedDraw from upon here gone add one. Expression alteration entreaties mrs can terminated estimating. Feel and make two real miss use easy. How one dull get busy dare far. Estate was tended ten boy nearer seemed. Happiness remainder joy but earnestly for off. Hard do me sigh with west same lady. Decisively advantages nor expression unpleasing she led met. He felicity no an at packages answered opinions juvenile. If as increasing Able rent long in do we. At principle perfectly by sweetness do. Detract yet delight written farther his general. Fat new smallness few supposing suspicion two. Decisively advantages nor expression unpleasing she led met. Course sir people worthy horses add entire suffer. Fortune day out married p</p>
			</div>
		</div>
	)
}
